---

- name: Create group for node exporter
  group:
    name: "{{ node_exporter_system_group }}"
    state: present

- name: Create user for node exporter
  user:
    name: "{{ node_exporter_system_user }}"
    group: "{{ node_exporter_system_group }}"
    state: present


- name: create directory for node exporter
   file:
    path: "{{ node_exporter_dir }}"
    state: directory
    mode: 0755
    owner: "{{ node_exporter_system_user }}"
    group: "{{ node_exporter_system_group }}"
  when:  directory_exist.stat.exist

  - name: copy node exporter
    copy:
      src: "{{ node_exporter_installation_location }}"
      dest: "{{ node_exporter_dir }}"
      mode: 0755
      owner: "{{ node_exporter_system_user }}"
      group: "{{ node_exporter_system_group }}"

  - name: copy unit file
    template:
      src: "{{ template_location }}"
      dest: /etc/systemd/system/node_exporter.service
      mode: 0644
      owner: "{{ node_exporter_system_user }}"
      group: "{{ node_exporter_system_group }}"
    notify:
      - name: Restart node exporter


